<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2"/>
<globals/>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="fil.20220612153831.3"><vh>sdfsdf</vh></v>
<v t="fil.20220612154243.1"><vh> modified</vh></v>
</vnodes>
<tnodes>
<t tx="fil.20220612153831.3"></t>
<t tx="fil.20220612154243.1"></t>
</tnodes>
</leo_file>
